### PR TITLE
fix merch prizes randomness

### LINKED ISSUE #9: fix randomness for merchandise prizes

### PR DESCRIPTION
**Pull request by Fraank98**

### CODE REVIEW

File: src/fortune-wheel-booth-frontend/src/utils/findPrize.ts [hunk 1]
```diff
@@ -1,6 +1,11 @@
 import { PRIZES } from '../costants';
 
 export const findPrize = (option: string) => {
-  const prize = PRIZES.find((prize, index) => prize.option === option);
-  return prize ? PRIZES.indexOf(prize) : 99; // TODO: Fix this, 99 represents "no prize exists for this option"
+  if (option === 'merch') {
+    const merchNumbers = [1, 2, 3, 4, 5, 6];
+    option =
+      'merch' + merchNumbers[Math.floor(Math.random() * merchNumbers.length)];
```
Comment (ilbertt) [inline src/fortune-wheel-booth-frontend/src/utils/findPrize.ts]: I think with Math.floor you never get the `merch6` option

File: src/fortune-wheel-booth-frontend/src/utils/findPrize.ts [hunk 2]
```diff
@@ -1,6 +1,11 @@
 import { PRIZES } from '../costants';
 
 export const findPrize = (option: string) => {
-  const prize = PRIZES.find((prize, index) => prize.option === option);
-  return prize ? PRIZES.indexOf(prize) : 99; // TODO: Fix this, 99 represents "no prize exists for this option"
+  if (option === 'merch') {
+    const merchNumbers = [1, 2, 3, 4, 5, 6];
```
Comment (ilbertt) [inline src/fortune-wheel-booth-frontend/src/utils/findPrize.ts]: This is not so scalable, because if you change the prizes in the constants file you also have to change this array. We should rather keep this dynamic instead

File: src/fortune-wheel-booth-frontend/src/costants.ts [hunk 3]
```diff
@@ -47,12 +47,12 @@ export const PRIZES: WheelDataType[] = [
...
   },
   {
-    option: 'merch',
+    option: 'merch5',
     image: { uri: Astronaut, sizeMultiplier: 0.7, offsetY: 220 },
     style: { backgroundColor: '#FBB03C' },
   },
   {
-    option: 'merch',
+    option: 'merch6',
```
Comment (ilbertt) [inline src/fortune-wheel-booth-frontend/src/costants.ts]: By changing the names in this way, we never hit the `PRIZES_VALUES_MAPPING.merch` value anymore

File: src/fortune-wheel-booth-frontend/src/utils/findPrize.ts (hunk 2 above)
Comment (ilbertt) [reply src/fortune-wheel-booth-frontend/src/utils/findPrize.ts]: For example, getting all the ids of the merch options or the total count of the merch options inside the `PRIZES` array and extract randomly on those ids.
Not efficient but we're never going to have millions of prizes in the array I think

**Review by ilbertt — CHANGES_REQUESTED** [review]

File: src/fortune-wheel-booth-frontend/src/utils/findPrize.ts [hunk 4]
```diff
@@ -1,6 +1,11 @@
...
+    option =
+      'merch' + merchNumbers[Math.floor(Math.random() * merchNumbers.length)];
+  }
+  const prizeIndex = PRIZES.findIndex((prize) => prize.option === option);
+  return prizeIndex ?? 99; // TODO: Fix this, 99 represents "no prize exists for this option"
```
Comment (ilbertt) [inline src/fortune-wheel-booth-frontend/src/utils/findPrize.ts]: Why can't we just throw an error if the index is undefined? We expect it to be always defined and hence throwing an error is the proper way to "handle" this exception

**Review by ilbertt — CHANGES_REQUESTED** [review]

File: src/fortune-wheel-booth-frontend/src/utils/findPrize.ts (hunk 1 above)
Comment (Fraank98) [reply src/fortune-wheel-booth-frontend/src/utils/findPrize.ts]: Screen Shot 2024-05-24 at 12 16 22 PM

Comment (ilbertt) [reply src/fortune-wheel-booth-frontend/src/utils/findPrize.ts]: Woops yeah I misread the code, sorry

File: src/fortune-wheel-booth-frontend/src/costants.ts (hunk 3 above)
Comment (Fraank98) [reply src/fortune-wheel-booth-frontend/src/costants.ts]: You mixed up between `PRIZES_VALUES_MAPPING` and `PRIZES`

**Review by ilbertt — APPROVED** [review]
